### ISSUE TITLE
password fields not visible in existing plugins

### ISSUE THREAD

**Issue by passuff** [invoiceradar/releases#1]
I tried to use an existing plugin like "Klarmobil" for example but the password field is not visible.
I had to clone the script and edit the password field type to string to make it work:

```
    "password": {
      "type": "string",
      "title": "Password",
      "required": true
```
Pretty sure I'm doing something wrong. Any hint is appreciated....

**Comment by tobiaslins** [comment]
Thanks for the report!
Are you using MacOS or Windows?

I just checked and it looks fine for me on MacOS.
<img width="737" alt="image" src="https://github.com/user-attachments/assets/edb8b015-f79d-4c71-8156-4facdd7c2afd" />

**Comment by passuff** [comment]
I'm using windows. Same for the email plugin.

Tobias Lins ***@***.***> schrieb am Mo., 13. Jan. 2025, 18:40:

**Comment by tobiaslins** [comment]
Thanks! Is the input invisible & you can click it? Mind sending a screenshot please? Will take a look into this hopefully tomorrow!

**Comment by passuff** [comment]
![image](https://github.com/user-attachments/assets/89c6ee1f-9b88-436a-a0f9-4800935cd8ee)



![image](https://github.com/user-attachments/assets/22aec135-2a10-49fa-9290-aa0d8864f4e3)

**Comment by tobiaslins** [comment]
@passuff A new version was released that should fix this issue :) thanks for reporting!

**Comment by passuff** [comment]
![image](https://github.com/user-attachments/assets/f2306b3e-f5b6-48fc-b5fa-f40a0dee8545)
password box is working but port box is still not.
